In [1]:
import numpy as np

In [3]:
x = np.array([1, 2, 3])
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [13]:
print(np.zeros((3, 4), dtype='int'))
print(np.ones((3, 4), dtype = 'int'))
print(np.full((3, 4), 15))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[15 15 15 15]
 [15 15 15 15]
 [15 15 15 15]]


In [16]:
print(np.arange(10, 20).reshape(2, 5))

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [20]:
print(np.linspace(10, 13, 5))

[10.   10.75 11.5  12.25 13.  ]


In [26]:
print(np.eye((4), dtype = "int"))
print(np.eye(3, 4, dtype = "int"))
print(np.eye(3, 4, k = 2, dtype = "int"))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
[[0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


In [32]:
x = np.arange(10, 20).reshape(2, 5)
print(x)
print(x.shape)
print(x.size)
print(x.ndim)
print(len(x))
print(x.dtype)

[[10 11 12 13 14]
 [15 16 17 18 19]]
(2, 5)
10
2
2
int64


In [38]:
print(np.random.rand(3))
print(np.random.randn(5))
np.random.seed(3)
print(np.random.rand(5))
print(np.random.randint(32, 45, 5))

[0.01874801 0.04063074 0.2478883 ]
[ 0.27844092 -0.58089402 -0.15151488 -1.14743417 -0.61100002]
[0.5507979  0.70814782 0.29090474 0.51082761 0.89294695]
[42 43 41 41 42]


In [ ]:
list = [2, 3, 3, 4, 5, 6, 5]
print(np.random.choice(list, 4))
print(np.random.choice(list, 4, replace = False)) #replace = False means that dont select the same index again not the same value again

[2 4 3 4]
[5 4 3 3]


In [44]:
arr = np.arange(10)
print(arr)
np.random.shuffle(arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[3 9 5 2 1 8 0 6 7 4]


In [60]:
#axis = 0 means column wise and axis = 1 means row wise 
arr = np.arange(6).reshape(2, 3)
print(arr)
print(arr.min())
print(arr.min(axis = 0))
print(arr.min(axis = 1))
print(arr.max())
print(arr.max(axis = 0))
print(arr.max(axis = 1))
print(arr.sum())
print(arr.sum(axis = 0))
print(arr.sum(axis = 1))
print(arr.mean())
print(arr.std())
print(np.median(arr))

[[0 1 2]
 [3 4 5]]
0
[0 1 2]
[0 3]
5
[3 4 5]
[2 5]
15
[3 5 7]
[ 3 12]
2.5
1.707825127659933
2.5


In [ ]:
arr = np.arange(24).reshape(4, -1)
print(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [66]:
x = np.arange(10)
arr1 = x[:, np.newaxis]
print(arr1)
arr2 = x[np.newaxis, :]
print(arr2)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[0 1 2 3 4 5 6 7 8 9]]


In [ ]:
#FLATTEN - DEEP (FD) & RAVEL - SHALLOW (RS) makes to 1d array from ndarray 
arr = np.arange(12).reshape(4, 3)

arr1 = arr.ravel()
arr1[2] = 99

arr2 = arr.flatten()
arr2[4] = 100

print(arr)
print(arr1)
print(arr2)

[[ 0  1 99]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1 99  3  4  5  6  7  8  9 10 11]
[  0   1  99   3 100   5   6   7   8   9  10  11]


In [80]:
# np.vstack() and np.hstack - Vertical and Horizontal Stacking 
arr1 = np.array([[1, 3, 4], 
                 [2, 3, 5]
                 ])
arr2 = np.array([[5, 6, 7], 
                 [8, 9, 10], 
                 [10, 11, 14]
                 ])
arr3 = np.arange(12).reshape(2, 6)

arr4 = np.hstack((arr1, arr3))
print(arr4)
arr5 = np.vstack((arr1, arr2))
print(arr5)

[[ 1  3  4  0  1  2  3  4  5]
 [ 2  3  5  6  7  8  9 10 11]]
[[ 1  3  4]
 [ 2  3  5]
 [ 5  6  7]
 [ 8  9 10]
 [10 11 14]]


In [82]:
print(np.concatenate((arr1, arr3), axis = 1))

[[ 1  3  4  0  1  2  3  4  5]
 [ 2  3  5  6  7  8  9 10 11]]


In [88]:
arr = np.full((5, 6), 35)
print(arr)

np.fill_diagonal(arr, 100)
print(arr)

[[35 35 35 35 35 35]
 [35 35 35 35 35 35]
 [35 35 35 35 35 35]
 [35 35 35 35 35 35]
 [35 35 35 35 35 35]]
[[100  35  35  35  35  35]
 [ 35 100  35  35  35  35]
 [ 35  35 100  35  35  35]
 [ 35  35  35 100  35  35]
 [ 35  35  35  35 100  35]]
